version: '3.7'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        POSTGRES_USER: "${POSTGRES_USER}"
    env_file: 
        - ".env"
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
  metabase:
    image: metabase/metabase
    restart: unless-stopped
    environment:
        MB_DB_FILE: '/metabase-data/metabase.db'
        MB_DB_TYPE: 'postgres'
        MB_DB_DBNAME: "${POSTGRES_USER}"
        MB_DB_PORT: '5432'
        MB_DB_USER: "${POSTGRES_USER}"
        MB_DB_HOST: 'postgres'
        MB_DB_PASS: "${POSTGRES_PASSWORD}"
    ports:
        - '127.0.0.1:8055:3000'
    env_file: 
        - ".env"
    volumes:
        - 'mb-data:/metabase-data'
    depends_on:
        - 'postgres'
  nginx:
    image: nginx:stable
    ports:
        - 8080:8080
    depends_on:
        - 'metabase'
    volumes: 
        - "./nginx-service.conf:/etc/nginx/conf.d/default.conf"

volumes:
  db-data:
  mb-data: